# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Indicamos cómo instalar dependencias con Poetry
python:
  install:
    - method: poetry
      path: .

# Directorio donde está tu documentación
sphinx:
  configuration: docs/source/conf.py

# Habilita artefactos (HTML, PDF, EPUB)
formats:
  - htmlzip
  - pdf
  - epub